import hashlib
import typing

# You may find these helpful
from decimal import *
import math
import string

# Helper functions

# The code for the Extended Euclidean Algorithm is adapted from the following website
# https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm access date 10/21
def extended_gcd(a, b):
    s = 0
    r = b
    old_s = 1
    old_r = a
    
    while ( r != 0 ):
        quotient = old_r // r
        old_r, r = r, old_r - quotient * r
        old_s, s = s, old_s - quotient * s

    if ( b != 0 ):
        bezout_t = (old_r - old_s * a) // b
    else:
        bezout_t = 0
    
    return old_r, old_s, bezout_t # gcd, coefficient1, coefficient2

# gcd modifed from "The mechanics of compromising low entropy RSA keys" accessed 10/25
# source: https://media.defcon.org/DEF%20CON%2029/DEF%20CON%2029%20presentations/Austin%20Allshouse%20-%20The%20Mechanics%20of%20Compromising%20Low%20Entropy%20RSA%20Keys.pdf
def gcd (a, b): 
    # Modified to avoid recursive call
    while (b != 0):
        a, b = b, a % b
    return a
    
# The code for the Vigenere encryption and decryption is adapted from the following website listed in the problem description
# https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher access date 10/18
# 
# Specifically:
#
# Vigenere can also be described algebraically. If the letters A–Z are taken to be the numbers 0–25, and addition is performed modulo 26, 
# Vigenere encryption E using the key K can be written as Ci = Ek(Mi) = (Mi + Ki) mod 26 
# and decryption D using the key K can be written as Mi = Dk(Ci) = (Ci - Ki) mod 26
# M = M1... Mn message
# C = C1... Cn ciphertext
# K = K1... Kn key obtained by repeating the keyword [n/m] times in which m is the keyword length

# ---------- PASSED TEST ---------- 
def vigenere_decrypt_cipher(c: str, keyword: str) -> str:

    # -------- Create Keyword --------
    
    # keyword has to match the length of m, so needs to be expanded before use
    temp_keyword = []

    stripped_c = [] # Stripping out all special chars and converting to uppercase
    for character in c:
        if ( character.isalpha() ):
            stripped_c.append( character.upper() )

    c = "".join(stripped_c)

    i = 0 # keeping track of temp_keyword index
    for character in c:
        temp_keyword.append( keyword[i % len(keyword)] ) # mod for cycling like going through a set of cards
        i = i + 1

    temp_keyword = ''.join(temp_keyword)
    
    # -------- Decryption Logic --------
    decrypted_m = []

    for i, character in enumerate(c):
        delta = (ord(character) - (ord(temp_keyword[i]) ) ) % 26 
        cipher = chr( delta + ord('A'))
        decrypted_m.append(cipher)

    m = ''.join(decrypted_m)
    return m

# ---------- PASSED TEST ---------- 
def vigenere_encrypt_message(m: str, keyword: str) -> str:

    # -------- Create Keyword --------

    # keyword has to match the length of m, so needs to be expanded before use
    temp_keyword = []

    stripped_m = [] # Stripping out all special chars and converting to uppercase
    for character in m:
        if ( character.isalpha() ):
            stripped_m.append( character.upper() )

    m = "".join(stripped_m)

    i = 0 # keeping track of temp_keyword index
    for character in m:
        temp_keyword.append( keyword[i % len(keyword)] ) # mod for cycling like going through a set of cards
        i = i + 1

    temp_keyword = ''.join(temp_keyword)
    
    # -------- Encryption Logic --------
    encrypted_m = []

    for i, character in enumerate(m):
        delta = (ord(character) + (ord(temp_keyword[i]) ) ) % 26 
        cipher = chr( delta + ord('A'))
        encrypted_m.append(cipher)

    c = ''.join(encrypted_m)

    return c

# ---------- PASSED TEST ---------- 
def vigenere_dictionary_attack(c: str) -> str:
    for item in DICTIONARY: # Pull an item to test it for cipher key decryption
        message = vigenere_decrypt_cipher(c, item) 

        found_words = 0

        for item2 in DICTIONARY: # Message contains dictionary words, test how compatible we are
            if ( message.find(item2) != -1):
                found_words = found_words + 1 # Increment, multiple words found increases likelihood of correct decryption
                if (found_words >= 3): # Threes get degrees
                    return message

    m = ''
    return m

# ---------- PASSED TEST ----------
def rsa_decrypt_cipher(n: int, d: int, c: int) -> int:
    m = 0
    m = pow(c, d, n) # Simple function call

    return m

# ---------- PASSED TEST ----------
def rsa_encrypt_message(m: int, e: int, n: int) -> int:
    c = 0
    c = pow(m, e, n) # Simple function call

    return c

# ---------- PASSED TEST ----------
def rsa_calculate_private_key(e: int, p: int, q: int) -> int:

    d = 0
    phi = (p -1) * (q-1)
    gcd, x, y = extended_gcd( e, phi )
    d = x % phi

    return d

# ---------- PASSED TEST ----------
def rsa_factor_64_bit_key() -> typing.Dict[str, typing.Dict[str, int]]:
    return {
        'test_1': {
            'p': 981725527,
            'q': 976660907
        },
        'test_2': {
            'p': 963948511,
            'q': 979214941
        },
        'test_3': {
            'p': 963258767,
            'q': 970832237
        },
        'test_4': {
            'p': 969260407,
            'q': 977176463
        },
        'test_5': {
            'p': 979592293,
            'q': 965077331
        }
    }

# ---------- PASSED TEST ----------
def rsa_weak_key_attack(given_public_key_N: int, given_public_key_e: int, public_key_list: typing.List[int]) -> int:
    # Source: https://factorable.net/weakkeys12.extended.pdf
    # d = e^-1 mod (p-1)(q-1)
    # When p and q are unknown, the most efficient known method to calculate the private key
    # is to factor N into p and q and use the above equation to
    # calculate d 

    # Calculate GCDs to find one with a shared prime
    for N_item in public_key_list:
        p = gcd(given_public_key_N, N_item)

        # Check for one with a shared prime
        if ( p > 1 ):
            q = given_public_key_N // p
            phi = (p-1) * (q-1)
            d = pow(given_public_key_e, -1, phi)

    return d

# ---------- PASSED TEST ----------
def rsa_broadcast_attack(N_1: int, c_1: int, N_2: int, c_2: int, N_3: int, c_3: int) -> int:
    # Source: https://en.wikipedia.org/wiki/Coppersmith%27s_attack
    # Date accessed: 10/26
    
    # c = m^e mod N
    # m = x^e mod N

    # Chinese Remainder referenced by Hastad's broadcast attack
    N_tot = N_1 * N_2 * N_3
    Inv_1 = pow( N_tot // N_1, -1, N_1 )
    Inv_2 = pow( N_tot // N_2, -1, N_2 )
    Inv_3 = pow( N_tot // N_3, -1, N_3 )

    C_factor1 = c_1 * (N_tot // N_1) * Inv_1
    C_factor2 = c_2 * (N_tot // N_2) * Inv_2
    C_factor3 = c_3 * (N_tot // N_3) * Inv_3  
    temp = ( C_factor1 + C_factor2 + C_factor3 ) % N_tot 

    # Not sure if right, but assuming that the result will be an int lets me binary search for the cube root...
    low, high = 0, temp
    while low < high: 
        mid = (low + high) // 2 + 1
        if mid * mid * mid <= temp: # e = 3 per problem description
            low = mid
        else:
            high = mid - 1

    m = low

    return m

DICTIONARY = [
    'INFORMATION', 'AVAILABLE', 'COPYRIGHT', 'UNIVERSITY', 'MANAGEMENT', 'INTERNATIONAL', 'DEVELOPMENT', 'EDUCATION', 'COMMUNITY', 'TECHNOLOGY', 'FOLLOWING', 'RESOURCES',
    'INCLUDING', 'DIRECTORY', 'GOVERNMENT', 'DEPARTMENT', 'DESCRIPTION', 'INSURANCE', 'DIFFERENT', 'CATEGORIES', 'ACCESSORIES', 'SEPTEMBER', 'QUESTIONS', 'APPLICATION',
    'FINANCIAL', 'EQUIPMENT', 'PERFORMANCE', 'EXPERIENCE', 'IMPORTANT', 'ACTIVITIES', 'ADDITIONAL', 'SOMETHING', 'PROFESSIONAL', 'COMMITTEE', 'WASHINGTON', 'CALIFORNIA',
    'REFERENCE', 'COMPANIES', 'COMPUTERS', 'PRESIDENT', 'AUSTRALIA', 'DISCUSSION', 'ENTERTAINMENT', 'AGREEMENT', 'MARKETING', 'ASSOCIATION', 'COLLECTION', 'SOLUTIONS',
    'TECHNICAL', 'MICROSOFT', 'CONFERENCE', 'ENVIRONMENT', 'STATEMENT', 'DOWNLOADS', 'INDIVIDUAL', 'SUBSCRIBE', 'EVERYTHING', 'PRODUCTION', 'COMMERCIAL', 'ADVERTISING',
    'TREATMENT', 'NEWSLETTER', 'KNOWLEDGE', 'CURRENTLY', 'CONSTRUCTION', 'REGISTERED', 'PROTECTION', 'ENGINEERING', 'PUBLISHED', 'CORPORATE', 'CUSTOMERS', 'MATERIALS',
    'COUNTRIES', 'STANDARDS', 'POLITICAL', 'ADVERTISE', 'ENVIRONMENTAL', 'AVAILABILITY', 'EMPLOYMENT', 'COMMISSION', 'ADMINISTRATION', 'INSTITUTE', 'SPONSORED', 'ELECTRONIC',
    'CONDITION', 'EFFECTIVE', 'ORGANIZATION', 'SELECTION', 'CORPORATION', 'EXECUTIVE', 'NECESSARY', 'ACCORDING', 'PARTICULAR', 'FACILITIES', 'OPPORTUNITIES', 'APPROPRIATE',
    'STATISTICS', 'INVESTMENT', 'CHRISTMAS', 'REGISTRATION', 'FURNITURE', 'WEDNESDAY', 'STRUCTURE', 'DISTRIBUTION', 'INDUSTRIAL', 'POTENTIAL', 'RESPONSIBLE', 'ASSOCIATED',
    'FOUNDATION', 'DOCUMENTS', 'COMMUNICATION', 'INDEPENDENT', 'OPERATING', 'DEVELOPED', 'TELEPHONE', 'POPULATION', 'NAVIGATION', 'THEREFORE', 'CHRISTIAN', 'UNDERSTAND',
    'WORLDWIDE', 'CONNECTION', 'PUBLISHER', 'INTRODUCTION', 'PROPERTIES', 'ACCOMMODATION', 'EXCELLENT', 'OPPORTUNITY', 'ASSESSMENT', 'ESPECIALLY', 'INTERFACE', 'OPERATION',
    'BEAUTIFUL', 'LOCATIONS', 'SIGNIFICANT', 'TECHNOLOGIES', 'MANUFACTURER', 'PROVIDING', 'AUTHORITY', 'CONSIDERED', 'PROGRAMME', 'ENTERPRISE', 'EDUCATIONAL', 'EMPLOYEES',
    'ALTERNATIVE', 'PROCESSING', 'RESPONSIBILITY', 'RESOLUTION', 'PUBLICATION', 'RELATIONS', 'PHOTOGRAPHY', 'ASSISTANCE', 'COMPLETED', 'OTHERWISE', 'TRANSPORTATION', 'DISCLAIMER',
    'MEMBERSHIP', 'RECOMMENDED', 'BACKGROUND', 'CHARACTER', 'MAINTENANCE', 'FUNCTIONS', 'PHENTERMINE', 'SUBMITTED', 'TELEVISION', 'INTERESTED', 'THROUGHOUT', 'ESTABLISHED',
    'PROGRAMMING', 'REGARDING', 'INCREASED', 'UNDERSTANDING', 'BEGINNING', 'BUSINESSES', 'SPECIFIED', 'RESTAURANT', 'RELATIONSHIP', 'TRADITIONAL', 'SOMETIMES', 'THEMSELVES',
    'TRANSPORT', 'INTERESTING', 'EVALUATION', 'IMPLEMENTATION', 'GALLERIES', 'PRESENTED', 'LITERATURE', 'RESPECTIVE', 'DEFINITION', 'SECRETARY', 'NETWORKING', 'AUSTRALIAN',
    'MAGAZINES', 'FRANCISCO', 'GUIDELINES', 'INSTALLATION', 'DESCRIBED', 'ATTENTION', 'DIFFERENCE', 'CERTIFICATE', 'DOCUMENTATION', 'AUTOMOTIVE', 'SUCCESSFUL', 'COMMUNITIES',
    'SITUATION', 'PUBLISHING', 'EMERGENCY', 'DEVELOPING', 'DETERMINE', 'TEMPERATURE', 'HISTORICAL', 'RINGTONES', 'DIFFICULT', 'SCIENTIFIC', 'SATELLITE', 'PARTICULARLY',
    'FUNCTIONAL', 'MONITORING', 'ARCHITECTURE', 'RECOMMEND', 'DICTIONARY', 'ACCOUNTING', 'MANUFACTURING', 'PROFESSOR', 'GENERALLY', 'CONTINUED', 'PERMISSION', 'GENERATION',
    'COMPONENT', 'GUARANTEE', 'PROCESSES', 'INTERESTS', 'PAPERBACK', 'SUPPORTED', 'COMPETITION', 'PROVIDERS', 'THOUSANDS', 'GENERATED', 'ADMINISTRATIVE', 'PRACTICES',
    'REPORTING', 'ESSENTIAL', 'AFFILIATE', 'IMMEDIATELY', 'DESIGNATED', 'INTEGRATED', 'CONFIGURATION', 'COMPREHENSIVE', 'UNIVERSAL', 'PRESENTATION', 'LANGUAGES', 'COMPLIANCE',
    'IMPROVEMENT', 'PENNSYLVANIA', 'CHALLENGE', 'ACCEPTANCE', 'STRATEGIES', 'MULTIMEDIA', 'CERTIFIED', 'COMPUTING', 'INTERACTIVE', 'PROCEDURE', 'LEADERSHIP', 'RELIGIOUS',
    'BREAKFAST', 'DEVELOPER', 'APPROXIMATELY', 'COMPARISON', 'AUTOMATICALLY', 'MINNESOTA', 'ADVENTURE', 'ASSISTANT', 'ADVERTISEMENT', 'HEADLINES', 'YESTERDAY', 'DETERMINED',
    'WHOLESALE', 'EXTENSION', 'COMPLETELY', 'ELECTRICAL', 'APPLICABLE', 'CLASSICAL', 'DEDICATED', 'DIRECTION', 'BASKETBALL', 'WISCONSIN', 'PERSONNEL', 'IDENTIFIED',
    'ADVANTAGE', 'ESTIMATED', 'ANONYMOUS', 'MISCELLANEOUS', 'INTEGRATION', 'INTERVIEW', 'FRAMEWORK', 'INSTALLED', 'MASSACHUSETTS', 'ASSOCIATE', 'FREQUENTLY', 'LABORATORY',
    'DESTINATION', 'INTELLIGENCE', 'TRIPADVISOR', 'RESIDENTIAL', 'DECISIONS', 'INDUSTRIES', 'PARTNERSHIP', 'EDITORIAL', 'EXPRESSION', 'REPLACEMENT', 'STRATEGIC', 'ECONOMICS',
    'COMPATIBLE', 'APARTMENT', 'NETHERLANDS', 'CONSULTING', 'RECREATION', 'FAVORITES', 'TRANSLATION', 'ESTIMATES', 'PROTECTED', 'PHILADELPHIA', 'OFFICIALS', 'CONTAINED',
    'LEGISLATION', 'TENNESSEE', 'REPRESENTATIVE', 'FREQUENCY', 'INTRODUCED', 'RESIDENTS', 'DISPLAYED', 'PERFORMED', 'ADMINISTRATOR', 'ADDRESSES', 'PERMANENT', 'AGRICULTURE',
    'PORTFOLIO', 'PRACTICAL', 'DELIVERED', 'INFRASTRUCTURE', 'EXCLUSIVE', 'ORIGINALLY', 'UTILITIES', 'PHILOSOPHY', 'REGULATION', 'REDUCTION', 'NUTRITION', 'RECORDING',
    'SECONDARY', 'WONDERFUL', 'ANNOUNCED', 'PREVENTION', 'MENTIONED', 'AUTOMATIC', 'HEALTHCARE', 'MAINTAINED', 'INCREASING', 'CONNECTED', 'DIRECTORS', 'PARTICIPATION',
    'CONTAINING', 'COMBINATION', 'AMENDMENT', 'GUARANTEED', 'LIBRARIES', 'DISTRIBUTED', 'SINGAPORE', 'CONVENTION', 'PRINCIPAL', 'CERTIFICATION', 'PREVIOUSLY', 'BUILDINGS',
    'HOUSEHOLD', 'BATTERIES', 'POSITIONS', 'SUBSCRIPTION', 'CONTEMPORARY', 'PANASONIC', 'PERMALINK', 'SIGNATURE', 'PROVISION', 'CERTAINLY', 'NEWSPAPER', 'LIABILITY',
    'TRADEMARK', 'TRACKBACK', 'AMERICANS', 'PROMOTION', 'CONVERSION', 'REASONABLE', 'BROADBAND', 'INFLUENCE', 'IMPORTANCE', 'WEBMASTER', 'PRESCRIPTION', 'SPECIFICALLY',
    'REPRESENT', 'CONSERVATION', 'LOUISIANA', 'JAVASCRIPT', 'MARKETPLACE', 'EVOLUTION', 'SUGGESTED', 'CONCERNED', 'ENCYCLOPEDIA', 'CONTINUING', 'INTERRACIAL', 'COMPETITIVE',
    'SUPPLIERS', 'PREPARATION', 'RECEIVING', 'ACCORDANCE', 'DISCUSSED', 'ELIZABETH', 'PLAYSTATION', 'INSTRUCTION', 'ANNOTATION', 'ESTABLISH', 'EXPRESSED', 'PARAGRAPH',
    'MATHEMATICS', 'COMPENSATION', 'CONDUCTED', 'PERCENTAGE', 'MISSISSIPPI', 'REQUESTED', 'CONNECTICUT', 'PERSONALS', 'IMMEDIATE', 'AGRICULTURAL', 'SUPPORTING', 'PARTICIPATE',
    'SPECIALIST', 'EXPERIENCED', 'INVESTIGATION', 'INSTITUTION', 'SEARCHING', 'TRANSMISSION', 'EXTREMELY', 'VERZEICHNIS', 'CONTRACTS', 'CONCERNING', 'EQUIVALENT', 'CHEMISTRY',
    'NEIGHBORHOOD', 'VARIABLES', 'CONTINUES', 'CURRICULUM', 'PSYCHOLOGY', 'RESPONSES', 'CIRCUMSTANCES', 'IDENTIFICATION', 'ELEMENTARY', 'UNLIMITED', 'PRINTABLE', 'ENFORCEMENT',
    'HARDCOVER', 'CELEBRITY', 'CHOCOLATE', 'HAMPSHIRE', 'BLUETOOTH', 'CONTROLLED', 'REQUIREMENT', 'AUTHORITIES', 'PREGNANCY', 'BIOGRAPHY', 'AUTHORIZED', 'RETIREMENT',
    'FINANCING', 'EFFICIENCY', 'EFFICIENT', 'COMMITMENT', 'SPECIALTY', 'QUALIFIED', 'DISCOVERY', 'CLASSIFIED', 'CONFIDENCE', 'LIFESTYLE', 'CONSISTENT', 'CLEARANCE',
    'INVENTORY', 'CONVERTER', 'ORGANISATION', 'OBJECTIVE', 'INDICATED', 'SECURITIES', 'VOLUNTEER', 'DEMOCRATIC', 'SWITZERLAND', 'PARAMETER', 'PROCESSOR', 'CONTRIBUTE',
    'RECOGNITION', 'SUBMISSION', 'ENCOURAGE', 'REGULATORY', 'INSPECTION', 'CONSUMERS', 'TERRITORY', 'TRANSACTION', 'MANCHESTER', 'CONTINUOUS', 'RESULTING', 'CAMBRIDGE',
    'INITIATIVE', 'EXECUTION', 'DISABILITY', 'INCREASES', 'CONTRACTOR', 'EXAMINATION', 'INDICATES', 'COMMITTED', 'EXTENSIVE', 'AFFORDABLE', 'CANDIDATE', 'DATABASES',
    'OUTSTANDING', 'PERSPECTIVE', 'MESSENGER', 'TOURNAMENT', 'CONSIDERATION', 'DISCOUNTS', 'CATALOGUE', 'CARIBBEAN', 'RESERVATION', 'REMAINING', 'DEPENDING', 'EXPANSION',
    'PURCHASED', 'PERFORMING', 'COLLECTED', 'ABSOLUTELY', 'FEATURING', 'IMPLEMENT', 'SCHEDULED', 'CALCULATOR', 'SIGNIFICANTLY', 'TEMPORARY', 'SUFFICIENT', 'AWARENESS',
    'VANCOUVER', 'CONTRIBUTION', 'MEASUREMENT', 'CONSTITUTION', 'PACKAGING', 'CONSULTATION', 'NORTHWEST', 'CLASSROOM', 'DEMOCRACY', 'WALLPAPER', 'MERCHANDISE', 'RESISTANCE',
    'BALTIMORE', 'CHARLOTTE', 'BIOLOGICAL', 'TRANSITION', 'INSTRUMENT', 'CLASSIFICATION', 'PHYSICIAN', 'HOLLYWOOD', 'WIKIPEDIA', 'SPIRITUAL', 'RELATIVELY', 'SATISFACTION',
    'PITTSBURGH', 'PREFERRED', 'INTELLECTUAL', 'COMFORTABLE', 'INTERACTION', 'LISTENING', 'EFFECTIVELY', 'EXPERIMENTAL', 'REVOLUTION', 'CONSOLIDATION', 'LANDSCAPE', 'DEPENDENT',
    'MECHANICAL', 'APPLICANT', 'COOPERATION', 'ACQUISITION', 'IMPLEMENTED', 'DIRECTORIES', 'RECOGNIZED', 'NOTIFICATION', 'LICENSING', 'TEXTBOOKS', 'DIVERSITY', 'CLEVELAND',
    'ACCESSIBILITY', 'SENSITIVE', 'TEMPLATES', 'COMPLETION', 'UNIVERSITIES', 'TECHNIQUE', 'CALCULATE', 'ALEXANDER', 'BROADCAST', 'CONVERTED', 'ANNIVERSARY', 'SPECIFICATION',
    'ACCESSIBLE', 'ACCESSORY', 'TYPICALLY', 'REPRESENTATION', 'UNIPROTKB', 'CONSUMPTION', 'BIRMINGHAM', 'AFTERNOON', 'CONSULTANT', 'CONTROLLER', 'OWNERSHIP', 'LEGISLATIVE',
    'UNSUBSCRIBE', 'MOLECULAR', 'RESIDENCE', 'ATTORNEYS', 'OPERATORS', 'SUSTAINABLE', 'PHILIPPINES', 'STATISTICAL', 'INNOVATION', 'EMPLOYERS', 'ELECTIONS', 'STAINLESS',
    'HOSPITALS', 'EXCEPTION', 'SUCCESSFULLY', 'INDONESIA', 'PRIMARILY', 'CAPABILITIES', 'RECOMMENDATION', 'RECRUITMENT', 'ORGANIZED', 'IMPROVING', 'EXPENSIVE', 'EXPLAINED',
    'EXPERTISE', 'MECHANISM', 'JEWELLERY', 'EVENTUALLY', 'CONSIDERING', 'INNOVATIVE', 'CONCLUSION', 'DISORDERS', 'COLLABORATION', 'DETECTION', 'FORMATION', 'ENGINEERS',
    'PROPOSALS', 'MODERATOR', 'TUTORIALS', 'SETTLEMENT', 'COLLECTABLES', 'FANTASTIC', 'PURCHASING', 'APPOINTED', 'OPERATIONAL', 'CORRESPONDING', 'DETERMINATION', 'ANIMATION',
    'TELECOMMUNICATIONS', 'INSTRUCTOR', 'APPROACHES', 'DESIGNERS', 'MELBOURNE', 'BLACKJACK', 'ARGENTINA', 'POSSIBILITY', 'COMMISSIONER', 'DANGEROUS', 'RELIABILITY', 'UNFORTUNATELY',
    'RESPECTIVELY', 'ATTACHMENT', 'APPOINTMENT', 'WORKSHOPS', 'HURRICANE', 'REPRESENTED', 'MORTGAGES', 'RESPONSIBILITIES', 'CAREFULLY', 'PRODUCTIVITY', 'INVESTORS', 'UNDERGROUND',
    'DIAGNOSIS', 'PRINCIPLE', 'VACATIONS', 'CALCULATED', 'APPEARANCE', 'INCORPORATED', 'NOTEBOOKS', 'ALGORITHM', 'VALENTINE', 'INVOLVING', 'INVESTING', 'CHRISTOPHER',
    'ADMISSION', 'TERRORISM', 'PARLIAMENT', 'ALLOCATED', 'STRUCTURAL', 'MUNICIPAL', 'DESCRIBES', 'DISABILITIES', 'SUBSTANCE', 'PROHIBITED', 'ADDRESSED', 'SIMULATION',
    'CONCENTRATION', 'INTERPRETATION', 'BANKRUPTCY', 'OPTIMIZATION', 'DISCOVERED', 'PARTICIPATING', 'EXHIBITION', 'COMPOSITION', 'NATIONWIDE', 'DEFINITELY', 'EXISTENCE', 'COMMENTARY',
    'LIMOUSINES', 'IMMIGRATION', 'NECESSARILY', 'ATTRIBUTE', 'APPARENTLY', 'SURROUNDING', 'MOUNTAINS', 'POPULARITY', 'POSTPOSTED', 'COORDINATOR', 'OBVIOUSLY', 'FUNDAMENTAL',
    'SUBSTANTIAL', 'PROGRESSIVE', 'CHAMPIONSHIP', 'SACRAMENTO', 'IMPOSSIBLE', 'DEPRESSION', 'TESTIMONIALS', 'MEMORABILIA', 'CARTRIDGE', 'EXPLANATION', 'CINCINNATI', 'SUBSECTION',
    'ELECTRICITY', 'PERMITTED', 'WORKPLACE', 'CONFIRMED', 'INFECTION', 'ELIGIBILITY', 'INVOLVEMENT', 'PLACEMENT', 'VBULLETIN', 'SUBSEQUENT', 'MOTORCYCLE', 'DISCLOSURE',
    'ESTABLISHMENT', 'UNDERGRADUATE', 'OCCUPATION', 'DONATIONS', 'CITYSEARCH', 'RADIATION', 'SERIOUSLY', 'ELSEWHERE', 'POLLUTION', 'CONSERVATIVE', 'GUESTBOOK', 'EFFECTIVENESS',
    'DEMONSTRATE', 'ATMOSPHERE', 'EXPERIMENT', 'PURCHASES', 'FEDERATION', 'ASSIGNMENT', 'CHEMICALS', 'EVERYBODY', 'NASHVILLE', 'COUNSELING', 'ACCEPTABLE', 'SATISFIED',
    'MILWAUKEE', 'MEDICATION', 'WAREHOUSE', 'SHAREWARE', 'VIOLATION', 'CONFIGURE', 'STABILITY', 'SOUTHWEST', 'INSTITUTIONAL', 'EXPECTATIONS', 'INDEPENDENCE', 'METABOLISM',
    'PERSONALLY', 'EXCELLENCE', 'SOMEWHERE', 'RECOGNIZE', 'SCREENING', 'THUMBNAIL', 'FORGOTTEN', 'INTELLIGENT', 'EDINBURGH', 'OBLIGATION', 'REGARDLESS', 'RESTRICTED',
    'REPUBLICAN', 'MERCHANTS', 'ATTENDANCE', 'ARGUMENTS', 'AMSTERDAM', 'ANNOUNCEMENT', 'APPRECIATE', 'REGULARLY', 'CUSTOMIZE', 'TRADITION', 'EMISSIONS', 'COMPLAINT',
    'AFGHANISTAN', 'SCHOLARSHIP', 'GOVERNANCE', 'CAMCORDER', 'IMPLEMENTING', 'OURSELVES', 'CONVERSATION', 'CAPABILITY', 'PRODUCING', 'PRECISION', 'CONTRIBUTED', 'REPRODUCTION',
    'INGREDIENTS', 'FRANCHISE', 'REHABILITATION', 'MAINTAINING', 'RECEPTION', 'CORRECTLY', 'GEOGRAPHY', 'APPEARING', 'INTEGRITY', 'DISCRIMINATION', 'PROCESSED', 'IMPLICATIONS',
    'FUNCTIONALITY', 'INTERMEDIATE', 'EMOTIONAL', 'PLATFORMS', 'OVERNIGHT', 'GEOGRAPHIC', 'PRELIMINARY', 'DISTRICTS', 'INTRODUCE', 'PROMOTIONAL', 'CHEVROLET', 'GENERATOR',
    'SUSPENSION', 'CORRECTION', 'AUTHENTICATION', 'COMMUNICATE', 'SUPPLEMENT', 'SHOWTIMES', 'PROMOTING', 'MACHINERY', 'BANDWIDTH', 'PROBABILITY', 'DIMENSION', 'SCHEDULES',
    'QUARTERLY', 'ILLUSTRATED', 'CONTINENTAL', 'ALTERNATE', 'ACHIEVEMENT', 'AUTOMATED', 'PASSENGER', 'CONVENIENT', 'ORIENTATION', 'CHILDHOOD', 'FLEXIBILITY', 'JURISDICTION',
    'DISPLAYING', 'ENCOURAGED', 'DECLARATION', 'AUTOMATION', 'PREPARING', 'RECIPIENT', 'ATHLETICS', 'SOUTHEAST', 'DETERMINING', 'PERSONALIZED', 'CONDITIONING', 'DESTRUCTION',
    'INCREASINGLY', 'MIGRATION', 'BASICALLY', 'CONVENTIONAL', 'OCCUPATIONAL', 'ADJUSTMENT', 'DIFFICULTY', 'COLLECTIVE', 'COALITION', 'ENROLLMENT', 'PRODUCERS', 'COLLECTOR',
    'REPRESENTING', 'OBSERVATION', 'RESTORATION', 'CONVENIENCE', 'RETURNING', 'OPPOSITION', 'CONTAINER', 'DEFENDANT', 'CONFIRMATION', 'SUPERVISOR', 'BESTSELLERS', 'DEPARTURE',
    'MINNEAPOLIS', 'INTERVENTION', 'ATTRACTION', 'MODIFICATION', 'CUSTOMIZED', 'UNDERSTOOD', 'ASSURANCE', 'HAPPENING', 'METROPOLITAN', 'COMPILATION', 'VERIFICATION', 'ATTRACTIVE',
    'JEFFERSON', 'GARDENING', 'ORCHESTRA', 'POLYPHONIC', 'OUTSOURCING', 'ADJUSTABLE', 'ALLOCATION', 'DISCIPLINE', 'DEMONSTRATED', 'IDENTIFYING', 'ALPHABETICAL', 'DISPATCHED',
    'INSTALLING', 'VOLUNTARY', 'PHOTOGRAPHER', 'MESSAGING', 'CONSTRUCTED', 'ADDITIONS', 'REQUIRING', 'ENGAGEMENT', 'REFINANCE', 'CALENDARS', 'ARRANGEMENT', 'BIBLIOGRAPHY',
    'COMPATIBILITY', 'FURTHERMORE', 'COOPERATIVE', 'MEASURING', 'JACKSONVILLE', 'HEADQUARTERS', 'TRANSFERS', 'TRANSFORMATION', 'PERSONALITY', 'FACILITATE', 'SUBSCRIBER', 'PRIORITIES',
    'BOOKSTORE', 'PARENTING', 'INCREDIBLE', 'COMMONWEALTH', 'PHARMACEUTICAL', 'MANHATTAN', 'WORKFORCE', 'ORGANIZATIONAL', 'PORTUGUESE', 'EVERYWHERE', 'DISCHARGE', 'HALLOWEEN',
    'HAZARDOUS', 'METHODOLOGY', 'HOUSEWARES', 'REPUTATION', 'RESISTANT', 'DEMOCRATS', 'RECYCLING', 'SLIDESHOW', 'VARIATION', 'TRANSFERRED', 'PHOTOGRAPH', 'DISTRIBUTOR',
    'UNDERLYING', 'WRESTLING', 'PHOTOSHOP', 'GATHERING', 'PROJECTION', 'MATHEMATICAL', 'SPECIALIZED', 'DIAGNOSTIC', 'INDIANAPOLIS', 'CRITICISM', 'AUTOMOBILE', 'CONFIDENTIAL',
    'STATUTORY', 'NORTHEAST', 'DOWNLOADED', 'PAINTINGS', 'INJECTION', 'YORKSHIRE', 'PROTECTIVE', 'INITIALLY', 'INDICATOR', 'ELIMINATE', 'SUNGLASSES', 'PREFERENCE',
    'THRESHOLD', 'VENEZUELA', 'EXPLORATION', 'SEQUENCES', 'ASTRONOMY', 'TRANSLATE', 'ANNOUNCES', 'COMPRESSION', 'ESTABLISHING', 'CONSTITUTIONAL', 'PERFECTLY', 'INSTANTLY',
    'LITIGATION', 'BROADCASTING', 'HORIZONTAL', 'TERRORIST', 'INFORMATIONAL', 'ECOMMERCE', 'SUFFERING', 'PROSPECTIVE', 'ULTIMATELY', 'ARTIFICIAL', 'SPECTACULAR', 'COORDINATION',
    'CONNECTOR', 'AFFILIATED', 'ACTIVATION', 'NATURALLY', 'MITSUBISHI', 'UNDERWEAR', 'POTENTIALLY', 'INCLUSIVE', 'DIMENSIONAL', 'CONSIDERABLE', 'SELECTING', 'PANTYHOSE',
    'DIFFICULTIES', 'COMPLEXITY', 'CONSTANTLY', 'BARCELONA', 'PRESIDENTIAL', 'DOCUMENTARY', 'TERRITORIES', 'PALESTINIAN', 'LEGISLATURE', 'HOSPITALITY', 'PROCUREMENT', 'THEORETICAL',
    'EXERCISES', 'SURVEILLANCE', 'PROTOCOLS', 'HIGHLIGHT', 'SUBSTITUTE', 'INCLUSION', 'HOPEFULLY', 'BRILLIANT', 'EVALUATED', 'TERMINATION', 'AUTHENTIC', 'MONTGOMERY',
    'ARCHITECTURAL', 'LOUISVILLE', 'MACINTOSH', 'MOVEMENTS', 'AMENITIES', 'VIRTUALLY', 'AUTHORIZATION', 'PROJECTOR', 'COMPARATIVE', 'PSYCHOLOGICAL', 'SURPRISED', 'GENEALOGY',
    'EXPENDITURE', 'LIVERPOOL', 'CONNECTIVITY', 'SIMILARLY', 'COLLABORATIVE', 'EXCLUDING', 'COMMANDER', 'SUGGESTION', 'SPOTLIGHT', 'INVESTIGATE', 'CONNECTING', 'LOGISTICS',
    'PROPORTION', 'SIGNIFICANCE', 'SYMPOSIUM', 'PROTECTING', 'TRANSMITTED', 'INTENSIVE', 'SWITCHING', 'CORRESPONDENCE', 'SUPERVISION', 'SEPARATION', 'TESTIMONY', 'CELEBRITIES',
    'MANDATORY', 'BOUNDARIES', 'SYNDICATION', 'CELEBRATION', 'FILTERING', 'LUXEMBOURG', 'OFFENSIVE', 'DEPLOYMENT', 'SEPARATED', 'DIRECTIVE', 'GOVERNING', 'RETAILERS',
    'OCCASIONALLY', 'ATTENDING', 'RECRUITING', 'INSTRUCTIONAL', 'TRAVELING', 'BIOTECHNOLOGY', 'PRESCRIBED', 'CATHERINE', 'REPRODUCED', 'CALCULATION', 'CONSOLIDATED', 'OCCASIONS',
    'EQUATIONS', 'EXCEPTIONAL', 'QUEENSLAND', 'MUSICIANS', 'COMPOSITE', 'UNAVAILABLE', 'ESSENTIALLY', 'DESIGNING', 'BRUNSWICK', 'SENSITIVITY', 'PRESERVATION', 'STREAMING',
    'INTENSITY', 'TECHNOLOGICAL', 'SYNDICATE', 'ANTIVIRUS', 'ADDRESSING', 'DISCOUNTED', 'BANGLADESH', 'CONSTITUTE', 'CONCLUDED', 'DESPERATE', 'DEMONSTRATION', 'GOVERNMENTAL',
    'MANUFACTURED', 'GRADUATION', 'ADDICTION', 'SPRINGFIELD', 'SYNTHESIS', 'UNDEFINED', 'UNEMPLOYMENT', 'ENHANCEMENT', 'NEWCASTLE', 'SOCIETIES', 'BRAZILIAN', 'IDENTICAL',
    'PETROLEUM', 'NORWEGIAN', 'RETENTION', 'EXCHANGES', 'SOUNDTRACK', 'WONDERING', 'PROFESSION', 'SEPARATELY', 'PHYSIOLOGY', 'COLLECTING', 'PARTICIPANT', 'RECREATIONAL',
    'DOMINICAN', 'FRIENDSHIP', 'EXPANDING', 'PROVINCIAL', 'ROCHESTER', 'ADVERTISER', 'ENCRYPTION', 'DOWNLOADABLE', 'SOPHISTICATED', 'POSSESSION', 'LABORATORIES', 'STOCKINGS',
    'RESPONDENT', 'DESTROYED', 'MANUFACTURE', 'WORDPRESS', 'VULNERABILITY', 'ACCOUNTABILITY', 'CELEBRATE', 'ACCREDITED', 'APPLIANCE', 'COMPRESSED', 'SCHEDULING', 'MORTALITY',
    'THERAPEUTIC', 'IMPRESSIVE', 'ACCORDINGLY', 'ARCHITECT', 'CHALLENGING', 'MICROWAVE', 'ACCIDENTS', 'RELOCATION', 'DISCRETION', 'COSMETICS', 'REPOSITORY', 'CHRISTIANITY',
    'REALISTIC', 'GENERATING', 'CHRISTINA', 'CONGRESSIONAL', 'PHOTOGRAPHIC', 'MILLENNIUM', 'ACHIEVING', 'FISHERIES', 'REACTIONS', 'MACROMEDIA', 'COMPANION', 'DIVISIONS',
    'ADDITIONALLY', 'FELLOWSHIP', 'VICTORIAN', 'LITHUANIA', 'MASTERCARD', 'OBTAINING', 'DISTRIBUTE', 'DECORATIVE', 'ENLARGEMENT', 'CAMPAIGNS', 'CONJUNCTION', 'INSTANCES',
    'INDIGENOUS', 'VALIDATION', 'CORRUPTION', 'CHOLESTEROL', 'DIFFERENTIAL', 'SCIENTIST', 'STARSMERCHANT', 'ARTHRITIS', 'NEVERTHELESS', 'TRANSCRIPT', 'INFLATION', 'COMPOUNDS',
    'CONTRACTING', 'STRUCTURED', 'REASONABLY', 'GRADUATES', 'CONTROLLING', 'ARLINGTON', 'PARTICLES', 'EXTRAORDINARY', 'INDICATING', 'COORDINATE', 'EXCLUSIVELY', 'LIMITATION',
    'WIDESCREEN', 'ILLUSTRATION', 'CONSTRUCT', 'INQUIRIES', 'INSPIRATION', 'AFFECTING', 'DOWNLOADING', 'AGGREGATE', 'FORECASTS', 'COMPLICATED', 'SHOPZILLA', 'DECORATING',
    'SHAKESPEARE', 'CONFLICTS', 'TRAVELERS', 'OFFERINGS', 'INCORRECT', 'FURNISHINGS', 'GUATEMALA', 'PERCEPTION', 'RENAISSANCE', 'PATHOLOGY', 'ORDINANCE', 'CONFIGURED',
    'FESTIVALS', 'POSSIBILITIES', 'CONTRIBUTING', 'ANALYTICAL', 'CIRCULATION', 'ASSUMPTION', 'JERUSALEM', 'INVENTION', 'TECHNICIAN', 'ENQUIRIES', 'COGNITIVE', 'EXPLORING',
    'REGISTRAR', 'SUPPORTERS', 'WITHDRAWAL', 'PREDICTED', 'SASKATCHEWAN', 'CANCELLATION', 'MINISTERS', 'VETERINARY', 'PROSTORES', 'RELEVANCE', 'INCENTIVE', 'BUTTERFLY',
    'MECHANICS', 'NUMERICAL', 'REFLECTION', 'ACCOMPANIED', 'INVITATION', 'PRINCETON', 'SPIRITUALITY', 'MEANWHILE', 'PROPRIETARY', 'CHILDRENS', 'THUMBZILLA', 'PORCELAIN',
    'PICHUNTER', 'TRANSLATED', 'COLUMNISTS', 'CONSENSUS', 'DELIVERING', 'JOURNALISM', 'INTENTION', 'UNDERTAKEN', 'STATEWIDE', 'SEMICONDUCTOR', 'HAPPINESS', 'SUBSTANTIALLY',
    'IDENTIFIER', 'CONDUCTING', 'ACCOMPLISHED', 'IMPRESSION', 'CORRELATION', 'FRAGRANCE', 'NEIGHBORS', 'TRANSPARENT', 'CHARLESTON', 'CHAMPIONS', 'INAPPROPRIATE', 'COMPARING',
    'VOCATIONAL', 'PHARMACIES', 'INTRODUCING', 'APPRECIATED', 'ALBUQUERQUE', 'DISTINGUISHED', 'PROJECTED', 'SHAREHOLDERS', 'DEVELOPMENTAL', 'REGULATED', 'ANTICIPATED', 'COMPLETING',
    'COMPARABLE', 'CONFUSION', 'COPYRIGHTED', 'WARRANTIES', 'DOCUMENTED', 'KEYBOARDS', 'VULNERABLE', 'REFLECTED', 'RESPIRATORY', 'MAINSTREAM', 'EVALUATING', 'SUBCOMMITTEE',
    'MATERNITY', 'VOLLEYBALL', 'LIABILITIES', 'DECREASED', 'TOLERANCE', 'CREATIVITY', 'DESCRIBING', 'LIGHTNING', 'QUOTATIONS', 'INSPECTOR', 'BOOKMARKS', 'BEHAVIORAL',
    'RIVERSIDE', 'BATHROOMS', 'ABILITIES', 'INITIATED', 'NONPROFIT', 'LANCASTER', 'SUSPENDED', 'ATTITUDES', 'SIMULTANEOUSLY', 'INTEGRATE', 'SOCIOLOGY', 'SCREENSHOT',
    'CONFIDENT', 'RETRIEVED', 'OFFICIALLY', 'CONSORTIUM', 'DELICIOUS', 'PERIODICALLY', 'HUNGARIAN', 'REFERRING', 'TRANSFORM', 'EDUCATORS', 'VEGETABLE', 'HUMANITIES',
    'INDEPENDENTLY', 'ALIGNMENT', 'HENDERSON', 'BRITANNICA', 'COMPETITORS', 'VISIBILITY', 'CONSCIOUSNESS', 'ENCOUNTER', 'ACCESSING', 'ATTEMPTED', 'WITNESSES', 'ADMINISTERED',
    'STRENGTHEN', 'FREDERICK', 'AGGRESSIVE', 'SUBLIMEDIRECTORY', 'DISTURBED', 'SCULPTURE', 'MOTIVATION', 'PHARMACOLOGY', 'QUANTITIES', 'PETERSBURG', 'CONSISTENTLY', 'POWERPOINT',
    'OBITUARIES', 'PUNISHMENT', 'APPRECIATION', 'SUBSEQUENTLY', 'PROVIDENCE', 'RESTRICTION', 'INCORPORATE', 'TREASURER', 'LIGHTWEIGHT', 'TRANSCRIPTION', 'COMPLICATIONS', 'SCRIPTING',
    'REMEMBERED', 'SYNTHETIC', 'TESTAMENT', 'SPECIFICS', 'PARTIALLY', 'WILDERNESS', 'SPONSORSHIP', 'HEADPHONES', 'PROCEEDING', 'VOLKSWAGEN', 'UNCERTAINTY', 'BREAKDOWN',
    'RECONSTRUCTION', 'SUBSIDIARY', 'STRENGTHS', 'ENCOURAGING', 'FURNISHED', 'BENEFICIAL', 'VIEWPICTURE', 'THREATENED', 'DISCUSSES', 'RESPONDED', 'ABSTRACTS', 'PREDICTION',
    'THESAURUS', 'INDIVIDUALLY', 'BATTLEFIELD', 'LITERALLY', 'ECOLOGICAL', 'APPRAISAL', 'CONSISTING', 'SUBMITTING', 'CITATIONS', 'GEOGRAPHICAL', 'MOZAMBIQUE', 'SHEFFIELD',
    'FINISHING', 'WELLINGTON', 'PROSPECTS', 'BULGARIAN', 'ABORIGINAL', 'REMARKABLE', 'PREVENTING', 'PRODUCTIVE', 'BOULEVARD', 'COMPLIANT', 'PENALTIES', 'IMAGINATION',
    'REFURBISHED', 'ACTIVATED', 'CONFERENCING', 'ARMSTRONG', 'POLITICIANS', 'ACCOMMODATE', 'CHRISTINE', 'ACCEPTING', 'PRECIPITATION', 'ISOLATION', 'SUSTAINED', 'APPROXIMATE',
    'PROGRAMMER', 'GREETINGS', 'INHERITED', 'INCOMPLETE', 'CHRONICLE', 'LEGITIMATE', 'BIOGRAPHIES', 'INVESTIGATOR', 'PLAINTIFF', 'PRISONERS', 'MEDITERRANEAN', 'NIGHTLIFE',
    'ENTREPRENEUR', 'FREELANCE', 'EXCESSIVE', 'SCREENSAVER', 'VALUATION', 'UNEXPECTED', 'CIGARETTE', 'CHARACTERISTIC', 'METALLICA', 'CONSEQUENTLY', 'NARRATIVE', 'ACADEMICS',
    'QUANTITATIVE', 'SUBDIVISION', 'DISTINCTION', 'LIVESTOCK', 'EXEMPTION', 'SUSTAINABILITY', 'FORMATTING', 'NUTRITIONAL', 'NICARAGUA', 'AFFILIATION', 'RELATIVES', 'SATISFACTORY',
    'REVOLUTIONARY', 'BRACELETS', 'TELEPHONY', 'BREATHING', 'THICKNESS', 'GRAPHICAL', 'DISCUSSING', 'AEROSPACE', 'MEANINGFUL', 'MAINTAINS', 'SHORTCUTS', 'VOYEURWEB',
    'EXTENDING', 'SPECIFIES', 'ACCREDITATION', 'BLACKBERRY', 'MEDITATION', 'MICROPHONE', 'MACEDONIA', 'COMBINING', 'INSTRUMENTAL', 'ORGANIZING', 'KAZAKHSTAN', 'STANDINGS',
    'PARTITION', 'INVISIBLE', 'COMMODITY', 'KILOMETERS', 'THANKSGIVING', 'INDICATION', 'CONGRATULATIONS', 'CONSULTANCY', 'RESPONDING', 'PHYSICALLY', 'STAKEHOLDERS', 'HYDROCODONE',
    'CONSECUTIVE', 'ATTEMPTING', 'COMPETING', 'PENINSULA', 'ACCURATELY', 'CONSIDERS', 'MINISTRIES', 'VACANCIES', 'PARLIAMENTARY', 'ACKNOWLEDGE', 'THOROUGHLY', 'NOTTINGHAM',
    'IDENTIFIES', 'QUESTIONNAIRE', 'QUALIFICATION', 'MODELLING', 'MINIATURE', 'INTERSTATE', 'CONSEQUENCE', 'SYSTEMATIC', 'PERCEIVED', 'MADAGASCAR', 'PRESENTING', 'TROUBLESHOOTING',
    'UZBEKISTAN', 'CENTURIES', 'MAGNITUDE', 'RICHARDSON', 'VOCABULARY', 'EARTHQUAKE', 'FUNDRAISING', 'GEOLOGICAL', 'ASSESSING', 'COMPUTATIONAL', 'ACDBENTITY', 'PARTICIPATED',
    'HANDHELDS', 'ANSWERING', 'IMPRESSED', 'CONSPIRACY', 'ORGANIZER', 'PRECEDING', 'CUMULATIVE', 'AMPLIFIER', 'ARBITRARY', 'PROMINENT', 'LEXINGTON', 'CONTACTED',
    'RECORDERS', 'OCCASIONAL', 'POSTCARDS', 'REVIEWING', 'EXPLICITLY', 'TRANSSEXUAL', 'CITIZENSHIP', 'INFORMATIVE', 'GIRLFRIEND', 'BLOOMBERG', 'HIERARCHY', 'INFLUENCED',
    'ABANDONED', 'COMPLEMENT', 'MAURITIUS', 'CHECKLIST', 'REQUESTING', 'LAUDERDALE', 'SCENARIOS', 'EXTRACTION', 'ELEVATION', 'UTILIZATION', 'BEVERAGES', 'CALIBRATION',
    'EFFICIENTLY', 'ENTERTAINING', 'PREREQUISITE', 'HYPOTHESIS', 'MEDICINES', 'REGRESSION', 'RENEWABLE', 'INTERSECTION', 'PASSWORDS', 'CONSISTENCY', 'AZERBAIJAN', 'ASTROLOGY',
    'OCCURRING', 'SUPPLEMENTAL', 'TRAVELLING', 'INDUCTION', 'PRECISELY', 'SPREADING', 'PROVINCES', 'WIDESPREAD', 'INCIDENCE', 'INCIDENTS', 'ENHANCING', 'INTERFERENCE',
    'PALESTINE', 'LISTPRICE', 'ATMOSPHERIC', 'KNOWLEDGESTORM', 'REFERENCED', 'PUBLICITY', 'PROPOSITION', 'ALLOWANCE', 'DESIGNATION', 'DUPLICATE', 'CRITERION', 'CIVILIZATION',
    'VIETNAMESE', 'TREMENDOUS', 'CORRECTED', 'ENCOUNTERED', 'INTERNATIONALLY', 'SURROUNDED', 'CREATURES', 'COMMENTED', 'ACCOMPLISH', 'VEGETARIAN', 'NEWFOUNDLAND', 'INVESTIGATED',
    'AMBASSADOR', 'STEPHANIE', 'CONTACTING', 'VEGETATION', 'FINDARTICLES', 'SPECIALLY', 'INFECTIOUS', 'CONTINUITY', 'PHENOMENON', 'CONSCIOUS', 'REFERRALS', 'DIFFERENTLY',
    'INTEGRATING', 'REVISIONS', 'REASONING', 'CHARITABLE', 'ANNOTATED', 'CONVINCED', 'BURLINGTON', 'REPLACING', 'RESEARCHER', 'WATERSHED', 'ACKNOWLEDGED', 'EQUILIBRIUM',
    'CHARACTERIZED', 'PRIVILEGE', 'QUALIFYING', 'ESTIMATION', 'PEDIATRIC', 'TECHREPUBLIC', 'BROCHURES', 'TRAVELLER', 'APPROPRIATIONS', 'SUSPECTED', 'BENCHMARK', 'BEGINNERS',
    'HIGHLIGHTED', 'STATIONERY', 'UNAUTHORIZED', 'COMPETENT', 'CONTRIBUTOR', 'GRADUALLY', 'DESIRABLE', 'JOURNALIST', 'AFTERWARDS', 'RELIGIONS', 'EXPLOSION', 'DAUGHTERS',
    'SIMPLIFIED', 'MOTHERBOARD', 'BIBLIOGRAPHIC', 'CHAMPAGNE', 'DEVIATION', 'SUPERINTENDENT', 'HOUSEWIVES', 'IRRIGATION', 'HYDRAULIC', 'ROBERTSON', 'PENETRATION', 'CONVICTION',
    'OMISSIONS', 'RETRIEVAL', 'QUALITIES', 'PROTOTYPE', 'IMPORTANTLY', 'APPARATUS', 'EXPLAINING', 'NOMINATION', 'EMPIRICAL', 'DEPENDENCE', 'SEXUALITY', 'POLYESTER',
    'SUGGESTING', 'REMAINDER', 'SPECIALIZING', 'COMMODITIES', 'CONCENTRATE', 'REPRODUCTIVE', 'MOLECULES', 'REFRIGERATOR', 'INTERVALS', 'SENTENCES', 'EXCLUSION', 'WORKSTATION',
    'HOLOCAUST', 'RECEIVERS', 'DISPOSITION', 'NAVIGATOR', 'MARIJUANA', 'CATHEDRAL', 'FAIRFIELD', 'FASCINATING', 'LAFAYETTE', 'COMPUTATION', 'CARDIOVASCULAR', 'SALVATION',
    'ACCOMPANYING', 'SELECTIVE', 'ARBITRATION', 'CONFIGURING', 'SACRIFICE', 'REMOVABLE', 'CONVERGENCE', 'GIBRALTAR', 'ANTHROPOLOGY', 'MALPRACTICE', 'REPORTERS', 'NECESSITY',
    'RENDERING', 'HEPATITIS', 'NATIONALLY', 'WATERPROOF', 'SPECIALTIES', 'HUMANITARIAN', 'FUNCTIONING', 'ECONOMIES', 'ALEXANDRIA', 'BACTERIAL', 'UNDERTAKE', 'CONTINUOUSLY',
    'CONVERTIBLE', 'SECRETARIAT', 'ADOLESCENT', 'CANCELLED', 'INTRODUCTORY', 'RESERVOIR', 'OCCURRENCE', 'WORCESTER', 'DEMOGRAPHIC', 'DISCIPLINARY', 'RESPECTED', 'PORTRAITS',
    'INTERPRETED', 'ELIMINATION', 'HYPOTHETICAL', 'IMMIGRANTS', 'COMPLIMENTARY', 'HELICOPTER', 'PERFORMER', 'POWERSELLER', 'GRADUATED', 'SURPRISING', 'UNNECESSARY', 'DRAMATICALLY',
    'YUGOSLAVIA', 'CHARACTERIZATION', 'LIKELIHOOD', 'CONTAMINATION', 'ENDANGERED', 'COMPROMISE', 'EXPIRATION', 'NAMESPACE', 'PERIPHERAL', 'NEGOTIATION', 'OPPONENTS', 'NOMINATED',
    'CONFIDENTIALITY', 'ELECTORAL', 'CHANGELOG', 'ALTERNATIVELY', 'GREENSBORO', 'CONTROVERSIAL', 'RECOVERED', 'UPGRADING', 'FRONTPAGE', 'DEMANDING', 'DEFENSIVE', 'FORBIDDEN',
    'MONITORED', 'DEUTSCHLAND', 'PRACTITIONER', 'MOTIVATED', 'SMITHSONIAN', 'EXAMINING', 'REVELATION', 'DELEGATION', 'DICTIONARIES', 'GREENHOUSE', 'TRANSPARENCY', 'CURRENCIES',
    'SURVIVORS', 'POSITIONING', 'DESCENDING', 'TEMPORARILY', 'FREQUENCIES', 'MUNICIPALITY', 'DETECTIVE', 'EXPERIENCING', 'FIREPLACE', 'ENDORSEMENT', 'PSYCHIATRY', 'PERSISTENT',
    'SUMMARIES', 'LOOKSMART', 'MAGNIFICENT', 'COLLEAGUE', 'ADAPTATION', 'PAINTBALL', 'ENCLOSURE', 'WESTMINSTER', 'DISTANCES', 'ABSORPTION', 'TREASURES', 'DISAPPOINTED',
    'CONTINUALLY', 'COMMUNIST', 'COLLECTIBLE', 'CREATIONS', 'BIODIVERSITY', 'EXCITEMENT', 'PRESENTLY', 'MYSTERIOUS', 'LIBRARIAN', 'SUBSIDIARIES', 'STOCKHOLM', 'INDONESIAN',
    'THERAPIST', 'PROMISING', 'RELAXATION', 'THEREAFTER', 'FORWARDING', 'NIGHTMARE', 'SOUTHAMPTON', 'ORGANISMS', 'TELESCOPE', 'PORTSMOUTH', 'ADVANCEMENT', 'HARASSMENT',
    'GENERATES', 'REPLICATION', 'INEXPENSIVE', 'RECEPTORS', 'HUNTINGTON', 'INTERNSHIP', 'ALUMINIUM', 'SNOWBOARD', 'BEASTALITY', 'EVANESCENCE', 'COORDINATED', 'SHIPMENTS',
    'ANTARCTICA', 'CHANCELLOR', 'CONTROVERSY', 'LEGENDARY', 'BEAUTIFULLY', 'ANTIBODIES', 'IMMUNOLOGY', 'DEPARTMENTAL', 'TERMINOLOGY', 'GENTLEMAN', 'REPRODUCE', 'CONVICTED',
    'ROOMMATES', 'THREATENING', 'SPOKESMAN', 'ACTIVISTS', 'FRANKFURT', 'ASSEMBLED', 'RESTRUCTURING', 'TERMINALS', 'SUFFICIENTLY', 'CONDITIONAL', 'CROSSWORD', 'CONCEPTUAL',
    'LIECHTENSTEIN', 'TRANSLATOR', 'CONTINENT', 'LONGITUDE', 'CHALLENGED', 'TELECHARGER', 'INSERTION', 'INSTRUMENTATION', 'CONSTRAINT', 'GROUNDWATER', 'STRENGTHENING', 'INSULATION',
    'INFRINGEMENT', 'SUBJECTIVE', 'SWAZILAND', 'VARIETIES', 'MEDIAWIKI'
]
